### PR TITLE
update example making it use stackplots and create Petroff colors objects

### PR DESCRIPTION
**Pull request by ttedeschi**

### CODE REVIEW

**Comment by clelange** [comment]
Thanks for addressing this promptly! I'm having a look at https://github.com/cms-cat/cmsstyle/blob/5046b07f6193e01789d4c119a23ac64f954faa7c/tests/pdfs/example_rectangle_pos0.pdf and see that the legend is the wrong way round. Data should be on top, then signal since it's above background.

**Comment by ttedeschi** [comment]
Fixed

**Comment by clelange** [comment]
Thanks again, much improved!
One remaining issue is that the legend of the lower panel in the ratio plots overlaps with the curves, see e.g. https://github.com/cms-cat/cmsstyle/blob/86e48a1052648a66203e12082b552001e30be6d7/tests/pdfs/example_rectangle_pos0_ratio.pdf

**Comment by ttedeschi** [comment]
done

**Comment by clelange** [comment]
We can also merge this now and address this separately, as you prefer.

**Review by clelange — APPROVED** [review]

**Pull request merged**
